# Dataset Loading

- Load the raw training text file

- Read the entire dataset into memory

- Inspect dataset size and preview content

In [1]:
with open("traindata.txt",'r',encoding='utf-8') as f:
       text=f.read()


In [2]:
print("The length of Data set:",len(text))

The length of Data set: 48151


In [3]:
print(text[:1000])

The Portrait of a Lady
A Photograph
“We’re Not Afraid to Die... if We
Can All Be Together”
Discovering Tut: the Saga
Continues
The Laburnum Top
The Voice of the Rain
The Ailing Planet: the Green
Movement’s Role
Childhood
The Adventure
Silk Road
Father to Son
Reprint 2025-26
Effective reading is receiving from others
their ideas and feelings.
Effective reading involves
 understanding the text
 talking about the text
 thinking about language
 working with words
 noticing form and patterns.
Reprint 2025-26
1. The Portrait of a Lady
Khushwant Singh
Notice these expressions in the text.
Infer their meaning from the context.
My grandmother, like everybody’s grandmother, was an old woman.
She had been old and wrinkled for the twenty years that I had known
her. People said that she had once been young and pretty and had
even had a husband, but that was hard to believe. My grandfather’s
portrait hung above the mantelpiece in the drawing room. He wore a
big turban and loose-fitting clothes.

In [4]:
chars=list(set(text))
vocab_size=len(chars)
print(''.join(chars))
print(vocab_size)

M824tH?,—:qBmIrhSY)’xGyF3vJP
(Lb c5sD6O1U_.K!jXfl–A”R-9w;…EZaenzdik‘7W0/u“N*CpTgoV
84


# Clean the Dataset

-Remove punctuation, digits, and symbols

# Keep only:

- alphabets
- spaces
- newline
- Convert text to lowercase

In [5]:
import re

with open("traindata.txt", "r", encoding="utf-8") as f:
    text = f.read()

# keep alphabets, spaces, and newline
text = re.sub(r"[^A-Za-z\s\n]", " ", text)

# clean extra spaces but keep line structure
text = re.sub(r"[ ]+", " ", text)

# convert to lowercase
text = text.lower()

with open("cleaned.txt", "w", encoding="utf-8") as f:
    f.write(text)

print("cleaning complete")

cleaning complete


# Load Cleaned Dataset

`` Load the processed dataset ``
```Check size and preview text ```

In [6]:
with open("cleaned.txt",'r',encoding='utf-8') as f:
       text2=f.read()

In [7]:
print(f"Lenght of the data set:{len(text2)} ")

Lenght of the data set:46532 


- First 1000 characters

In [8]:
print(text2[:1000])

the portrait of a lady
a photograph
 we re not afraid to die if we
can all be together 
discovering tut the saga
continues
the laburnum top
the voice of the rain
the ailing planet the green
movement s role
childhood
the adventure
silk road
father to son
reprint 
effective reading is receiving from others
their ideas and feelings 
effective reading involves
 understanding the text
 talking about the text
 thinking about language
 working with words
 noticing form and patterns 
reprint 
 the portrait of a lady
khushwant singh
notice these expressions in the text 
infer their meaning from the context 
my grandmother like everybody s grandmother was an old woman 
she had been old and wrinkled for the twenty years that i had known
her people said that she had once been young and pretty and had
even had a husband but that was hard to believe my grandfather s
portrait hung above the mantelpiece in the drawing room he wore a
big turban and loose fitting clothes his long white beard covered the

## Build Character Vocabulary

- Extract unique characters from dataset
- Compute vocabulary size
- chars → unique characters
- vocab_size → number of tokens in dataset

In [9]:
chars2=sorted(list(set(text2)))
vocab_size2=len(chars2)
print(''.join(chars2))
print(vocab_size2)


 abcdefghijklmnopqrstuvwxyz
28


## Encode and Decode Functions
 - Encode text → token IDs
 - Decode token IDs → text

In [10]:
stri = {ch:i for i, ch in enumerate(chars2)}
it = {i:ch for i, ch in enumerate(chars2)}

encode = lambda s: [stri[c] for c in s]# a function that take a string triverse it and return a integer list
decode = lambda l: ''.join([it[i] for i in l])# a function that convert the 

print(encode("eamon"))
print(decode(encode("eamon")))

[6, 2, 14, 16, 15]
eamon


## Convert Dataset to Tensor
- Convert encoded tokens to PyTorch tensor

In [11]:
import torch
data=torch.tensor(encode(text2),dtype=torch.long)
print(data.dtype,data.shape)

torch.int64 torch.Size([46532])


In [12]:
print(data[:1000])

tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16,  7,  1,  2,  1,
        13,  2,  5, 26,  0,  2,  1, 17,  9, 16, 21, 16,  8, 19,  2, 17,  9,  0,
         1, 24,  6,  1, 19,  6,  1, 15, 16, 21,  1,  2,  7, 19,  2, 10,  5,  1,
        21, 16,  1,  5, 10,  6,  1, 10,  7,  1, 24,  6,  0,  4,  2, 15,  1,  2,
        13, 13,  1,  3,  6,  1, 21, 16,  8,  6, 21,  9,  6, 19,  1,  0,  5, 10,
        20,  4, 16, 23,  6, 19, 10, 15,  8,  1, 21, 22, 21,  1, 21,  9,  6,  1,
        20,  2,  8,  2,  0,  4, 16, 15, 21, 10, 15, 22,  6, 20,  0, 21,  9,  6,
         1, 13,  2,  3, 22, 19, 15, 22, 14,  1, 21, 16, 17,  0, 21,  9,  6,  1,
        23, 16, 10,  4,  6,  1, 16,  7,  1, 21,  9,  6,  1, 19,  2, 10, 15,  0,
        21,  9,  6,  1,  2, 10, 13, 10, 15,  8,  1, 17, 13,  2, 15,  6, 21,  1,
        21,  9,  6,  1,  8, 19,  6,  6, 15,  0, 14, 16, 23,  6, 14,  6, 15, 21,
         1, 20,  1, 19, 16, 13,  6,  0,  4,  9, 10, 13,  5,  9, 16, 16,  5,  0,
        21,  9,  6,  1,  2,  5, 23,  6, 

## Train / Validation Split
`` Split dataset to detect overfitting ``
- 90% training
- 10% validation

In [13]:
# now split the data into train data and validation data
n=int(0.9*len(data))
train_data=data[:n]
val_data=data[n:]

In [14]:
block_size=18
train_data[:block_size+1]

tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16,  7,  1,  2,  1,
        13])

In [15]:
a=train_data[:block_size]
b=train_data[1:block_size+1]
for t in range(block_size):
       context=a[:t+1]
       target=b[t]
       print(f"Input:{context},target:{target}")

Input:tensor([21]),target:9
Input:tensor([21,  9]),target:6
Input:tensor([21,  9,  6]),target:1
Input:tensor([21,  9,  6,  1]),target:17
Input:tensor([21,  9,  6,  1, 17]),target:16
Input:tensor([21,  9,  6,  1, 17, 16]),target:19
Input:tensor([21,  9,  6,  1, 17, 16, 19]),target:21
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21]),target:19
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19]),target:2
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2]),target:10
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10]),target:21
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21]),target:1
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1]),target:16
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16]),target:7
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16,  7]),target:1
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16,  7,  1]),target:2
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1

- Context and Target Example
- Demonstrate next-token prediction

In [16]:
batch_size=4
block_size=18
torch.manual_seed(1337)
def get_batch(split):
       if split=='train':
              data=train_data
       else:
              data=val_data
       ix = torch.randint(len(data) - block_size, (batch_size,))
       x=torch.stack([data[i:i+block_size]for i in ix])
       y=torch.stack([data[i+1:i+block_size+1]for i in ix])
       return x,y

xb,yb=get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)
print("--------------------------------------")

for b in range(batch_size):
       for t in range(block_size):
              context=xb[b,:t+1]
              target=yb[b,t]
              print(f"context:{context} and target:{target} ")


inputs:
torch.Size([4, 18])
tensor([[ 8,  6,  5,  1, 17, 16, 19, 21,  1,  9, 22, 13, 13,  1,  7,  2,  4, 10],
        [22, 19,  6, 20,  1,  0, 16, 15,  6,  1,  5,  2, 26,  1, 10,  1,  2, 15],
        [ 2,  4, 12,  1, 16, 15,  0,  5,  6,  4, 12,  1, 24, 10, 21,  9,  1, 21],
        [22, 14, 17,  6,  5,  1, 21,  9,  6,  1, 20,  2,  8,  8, 10, 15,  8,  1]])
targets:
torch.Size([4, 18])
tensor([[ 6,  5,  1, 17, 16, 19, 21,  1,  9, 22, 13, 13,  1,  7,  2,  4, 10, 15],
        [19,  6, 20,  1,  0, 16, 15,  6,  1,  5,  2, 26,  1, 10,  1,  2, 15, 15],
        [ 4, 12,  1, 16, 15,  0,  5,  6,  4, 12,  1, 24, 10, 21,  9,  1, 21,  9],
        [14, 17,  6,  5,  1, 21,  9,  6,  1, 20,  2,  8,  8, 10, 15,  8,  1, 20]])
--------------------------------------
context:tensor([8]) and target:6 
context:tensor([8, 6]) and target:5 
context:tensor([8, 6, 5]) and target:1 
context:tensor([8, 6, 5, 1]) and target:17 
context:tensor([ 8,  6,  5,  1, 17]) and target:16 
context:tensor([ 8,  6,  5,  1, 17, 16]

### Bigram Language Model
- Predict next character based only on current character
- Uses embedding lookup

In [17]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size2)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([72, 28])
tensor(4.1525, grad_fn=<NllLossBackward0>)

o gczsr
iwsmm bjn rn xctpzdcyyhvnty
n xawrhmsfrcywkkmrqkpdxjufpglkprzot
gu
u
jnqectluy
kzr
qkpwoyr
j
